CSSS/wall_e

main.py
=> Syntax feedback

README.md
reorder text
clarify instruction
=> add more detail to the README

main.py
Fixes #15 
Fixes iamn command success message due to unrenamed variable
=> 15 fix whois list

main.py
Ability to delete empty roles.
=> Added .deleterole.

README.md
Added documentation on the `.deleterole` command to the README
=> Updated README.md to reflect .deleterole addition

.gitignore, main.py, requirements.txt
Added urban command to allow queries to urban dictionary. 
Updated the echo command to include invoking users name.
Updated whois command to uses users nicknames when available.
=> Urban dictionary feature

main.py, requirements.txt
will implement command to respond with a paginated list of roles in the channel itself after main script is modularized
=> adding command to dm list of roles to user

.dockerignore, Jenkinsfile, main.py, testenv.py
=> Test server now has a different channel and bot version for each branch

commands_to_load/Administration.py, commands_to_load/HealthChecks.py, main.py
I figured it would be nice to make the JSON output prettier on the logs side?
=> improving output legibility

main.py
=> last refactor

commands_to_load/RoleCommands.py, commands_to_load/help.json
splitting `.roles` into
- `.roles` for self-assignable roles and
- `.Roles` for XP/Minion and Exec assigned roles
=> Split roles into 2

commands_to_load/HealthChecks.py, commands_to_load/Mod.py, commands_to_load/cogs.json, commands_to_load/help.json
* allows mods to post a message in embed form
* if # of args is odd the first arg is put to the description and the rest as title content fields
* if # of args is even the no description and only fields
* posts a warning
=> Vj mod cog

.gitignore, Jenkinsfile, README.md, commands_to_load/Misc.py, commands_to_load/help.json, main.py, requirements.txt
The good ol' Wolfram command. Also I added stats_of_commands.csv to .gitignore to avoid committing/pushing it. Branch `wolfram` can be deleted after merging.
=> Wolfram Command

.gitignore, README.md, commands_to_load/Administration.py, commands_to_load/Here.py, commands_to_load/cogs.json, commands_to_load/help.json, main.py
useful for seeing who has access to a channel
=> here command

commands_to_load/Here.py
Add channel specific roles to output.
Move name and nick to their own column.
=> Here: Change formatting.

commands_to_load/Mod.py
=> changed the mod commands so they'll delete the invoking command even if

README.md
Categorized all the commands based on the files they are from and their respective uses.
=> Updated README.md for better readability

commands_to_load/Misc.py, requirements.txt
Prevent the urban command from blocking the entire bot incase of network issues by making it asynchronous.
=> Async urban

commands_to_load/HealthChecks.py, commands_to_load/Misc.py, commands_to_load/Mod.py, commands_to_load/Reminders.py, commands_to_load/RoleCommands.py, commands_to_load/SFU.py, helper_files/embed.py, main.py
changing the embed function into a co-routine and adding checks to ensure that all the parameters fit under the limits that discord placed on the embed aspects as describered [here](https://discordapp.com/developers/docs/resources/channel#embed-limits)
=> Validate all embeds

main.py
=> adding argument as I had initially forgotten to ..

commands_to_load/Mod.py
Council has requested to change "A Bellow from the Underworld" to "Attention" so that moderator warnings can be taken more seriously.
=> Change header to "Attention"

commands_to_load/Misc.py, commands_to_load/help.json
When people want emphasis.
Syntax:
`.emotespeak hello 123`
=> added emote speak

commands_to_load/Misc.py, commands_to_load/help.json
=> Revert "added emote speak"

commands_to_load/Misc.py, commands_to_load/help.json
=> Re-factor emojispeak here to avoid conflicts

commands_to_load/Reminders.py, commands_to_load/RoleCommands.py
=> removed debugging

helper_files/embed.py
=> Fix whois bug

helper_files/embed.py
=> analyze whois bug

helper_files/Paginate.py, helper_files/embed.py
fixed issue where messages werent being deleted
=> Fix paginate bug

documentation/Being_a_Bot_manager.md
Various changes were made to grammar, word choice, and sentence structure to improve readability. This pull request was made for a CMPT 376 assignment.
=> Changes to grammar and word choice.

documentation/Working_on_the_Bot.md
Various changes were made to grammar, word choice, and sentence structure to improve the readability of the documentation. This pull request was made for a CMPT 376 assignment.
=> Improved readability of documentation.

CI/server_scripts/Jenkinsfile, CI/server_scripts/deploy-to-test-server.sh
=> Ci master fix

wall_e/src/resources/utilities/config/config.py
=> Config debug

CI/server_scripts/Jenkinsfile_clean_branch, CI/server_scripts/Jenkinsfile_clean_pr
forgot the update the discord token when doing the general improvements.
=> fixing discord token so it uses the new id

wall_e/src/resources/cogs/manage_cog.py
used the wrong section when re-writing this code part. this pr fixes that
=> correcting section used for branch name

wall_e/src/resources/utilities/config/config.py
takes care of issue https://github.com/CSSS/wall_e/issues/243
=> turning off interpolation

wall_e/src/resources/cogs/manage_cog.py
=> swapping out the unnecessary long and duplicate message for something short and to the point

wall_e/src/resources/utilities/list_of_perms.py
optimizing the code for getting all the permissions that a user has
1. If you are adding a new command....document. Document the …
=> Improve get perms code

wall_e/src/resources/cogs/administration.py
adding a check to frequency so it cross-checks all inputs with column headers in the database to ensure user entered correct column headers
1. If your PR is doing something like adding a new line or removing a new line, CODEOWNERS reserve the right to ask that you undo that change unless it was for a specific …
=> Add frequency check

CI/server_scripts/create-dev-docker-image.sh, CI/server_scripts/create-prod-docker-image.sh, CI/server_scripts/deploy-to-prod-server.sh, CI/server_scripts/deploy-to-test-server.sh, CI/server_scripts/validate-formatting.sh, CI/user_scripts/test_walle.sh, wall_e/src/main.py, wall_e/src/resources/cogs/administration.py, wall_e/src/resources/cogs/health_checks.py, wall_e/src/resources/cogs/here.py, wall_e/src/resources/cogs/manage_cog.py, wall_e/src/resources/cogs/misc.py, wall_e/src/resources/cogs/mod.py, wall_e/src/resources/cogs/reminders.py, wall_e/src/resources/cogs/role_commands.py, wall_e/src/resources/cogs/sfu.py, wall_e/src/resources/utilities/config/config.py, wall_e/src/resources/utilities/database.py, wall_e/src/resources/utilities/embed.py, wall_e/src/resources/utilities/list_of_perms.py, wall_e/src/resources/utilities/log_channel.py, wall_e/src/resources/utilities/logger_setup.py, wall_e/src/resources/utilities/paginate.py, wall_e/src/resources/utilities/send.py, wall_e/test/test-requirements.txt
Description: this PR will enforce [PEP8 Naming Conventions](https://www.python.org/dev/peps/pep-0008/#naming-conventions) from now on.
1. If your PR is doing something like adding a new line or removing a new line, CODEOWNERS reserve the right to ask that you undo that change unless it was for a specific …
=> Implement naming conventions checking with linter

wall_e/src/main.py, wall_e/src/resources/cogs/administration.py, wall_e/src/resources/cogs/health_checks.py, wall_e/src/resources/cogs/here.py, wall_e/src/resources/cogs/manage_cog.py, wall_e/src/resources/cogs/misc.py, wall_e/src/resources/cogs/mod.py, wall_e/src/resources/cogs/reminders.py, wall_e/src/resources/cogs/role_commands.py, wall_e/src/resources/cogs/sfu.py
improving how cog discovery and loading works so there is no reliance on a function to get the name of the class that represents the cog.
1. If your PR is doing something like adding a new line or removing a new line, CODEOWNERS reserve the right to ask that you undo that change unless it was for a specific …
=> Refactor cog loading

wall_e/src/resources/utilities/database.py
Description: fix the reference to the sql file I had created a long time ago
1. If you are adding a new command....document. …
=> updating which commit contains the sql file

docs/pull_request_template.md
Description: updates the pr template with a provided description section and fixes the links in it. …
=> fixing references to test cases for wall_e

CI/server_scripts/build_wall_e/create-prod-docker-image.sh, wall_e/src/resources/utilities/config/production.ini
I had forgotten to make `branch_name` caps in my last PR
=> fixing typo

wall_e/src/resources/cogs/administration.py, wall_e/src/resources/cogs/manage_cog.py, wall_e/src/resources/cogs/misc.py, wall_e/src/resources/locales/help.json
This PR fixes 2 issues:
Bigger issue: wall_e currently needs each command to itself check and see if the invoker has access to it. This check has now been moved to a separate function under the `Manage_Cog` class called `check_privilege` as a bot.check functionality that is run every time a command is invoked.
Using this new way to do permission checking, the user's access to the command is now always verified against the access defined in the `help.json` entry for that command.
Smaller issue: all the command and functions that use the `help.json` file will now have it pre-loaded for them under the initializer for their class, instead of having to read it each time they are called. This is done to improve run-time for those functions.
These are the things you need to ensure are covered in …
=> Ensure perms are applied

CODEOWNERS, wall_e/src/resources/cogs/administration.py
apparently outputting the actual result of exc was accidentally removed in a previous commit. …
=> command to print output of exc re-added

CODEOWNERS, wall_e/src/resources/cogs/misc.py, wall_e/src/resources/locales/help.json
adding frequency command to `help.json` so that it can be used as well as updating the help command so that it follows the new way to determine who has access to a command and who does not.
1. If your PR is doing something like adding a new line or removing a new line, CODEOWNERS reserve the right to ask …
=> Add frequency to help

wall_e/src/resources/utilities/embed.py
fixing bug from issue https://github.com/CSSS/wall_e/issues/259
1. If you are adding a new command....document. Document the …
=> fixing bug with embed creation

wall_e/src/main.py, wall_e/src/resources/cogs/misc.py, wall_e/src/resources/utilities/database.py
fixing some flake8 issues
1. If you are adding a new command....document. Document the following things on help.json and the …
=> fixed flake8 issues

CI/destroy-dev-env.sh, CI/server_scripts/build_wall_e/deploy-to-test-server.sh, CI/server_scripts/clean_branch/clear_branch_env.sh, CI/server_scripts/clean_pr/clear_pr_env.sh
Ensuring that anonymous logs are also removed between commits for wall_e's that are deployed to the server.
1. If you are adding a …
=> Clean resources between test commits

CI/destroy-dev-env.sh, CI/server_scripts/clean_branch/clear_branch_env.sh, CI/server_scripts/clean_pr/clear_pr_env.sh
undoing winfield's suggestion as they dont make much of a difference
1. If you are adding a new command....document. Document the …
=> undoing fix set changes

documentation/Working_on_Bot/Test_Cases.md, wall_e/src/resources/cogs/reminders.py, wall_e/src/resources/locales/help.json
Currently, the user is already able to this, but for most users (i.e. those outside a UTC+0 timezone) it doesn't behave as expected, interpreting their time as UTC instead of their specific timezone. This PR fixes it so that a more sensible timezone is assumed, and the user can specify their own timezone otherwise.
As SFU's main campuses are in the Canada/Pacific timezone, .remindmein defaults to that timezone for any commands unless specified by the user. Note that this shouldn't be an issue at all with the base functionality (".remindmein 10 minutes to ..." sets the reminder in 10 minutes, irrespective of the timezone).
Resolves #216 
These are the things you need to ensure are covered in your PR, otherwise the CODEOWNERS will not approve your PR, not matter how much you ping them to do …
=> Create a reminder command that lets the user specify a date to be reminded on

CI/server_scripts/build_wall_e/Jenkinsfile
surrounding all the credentials with single quotes to deal with potetially ugly characters …
=> Fix jenkins env variables

wall_e/src/resources/cogs/manage_cog.py, wall_e/src/resources/cogs/misc.py, wall_e/src/resources/locales/help.json, wall_e/src/resources/utilities/config/config.py
re-doing the `help.json` file so that it is a dictionary of keys that each correspond to a bot command. This is done
1. to clean the format of the json file since the key `commands` was unnecessary.
1. when the user wanted to invoke the `help` command for a particular command, the code  previously had to look through each command until it found the one that the user had requested. the changed I implemented make it so that the code can just retrieve the command directly via the key.
1. remove the `class` entries as it never made much sense for them to be a separate entry and instead adding the `class` as an attribute of each command entry itself.
Going forward, this means that when a user adds a new command, if it a command under an existing class, they need to add it directly after the …
=> Improve help json reading efficiency

wall_e/src/resources/cogs/manage_cog.py
printing number of channels rather than a list of them since wall_e tends to disconnect from the guild quite frequently which leads to the logs being filled up the list of channels which is problematic on the production guild where we have over 100 channels.
1. If your PR is doing something like adding a new …
=> print number of channels

wall_e/src/main.py
Adding in code to see if I can glean a better understanding of why wall_e keeps disconnecting in PROD …
=> Investigate disconnection

wall_e/src/main.py
=> Revert "Investigate disconnection"

CI/server_scripts/build_wall_e/create_prod_docker_image.sh
=> fixing the script so that the correct origin name is specified for Dockerfile.wall_e_base file

CI/server_scripts/build_wall_e/create_prod_docker_image.sh
=> adding arg to docker command so that the dockerfile can see it

wall_e/src/requirements.txt
doing a version bump as discord introduced a breaking change recently:
2020-07-22 20:00:43 = WARNING - Traceback (most recent call last):
2020-07-22 20:00:43 = WARNING -   File "./main.py", line 139, in <module>
2020-07-22 20:00:43 = WARNING -     
2020-07-22 20:00:43 = WARNING - bot.run(WallEConfig.get_config_value("basic_config", "TOKEN"))
2020-07-22 20:00:43 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 598, in run
2020-07-22 20:00:43 = WARNING -     
2020-07-22 20:00:43 = WARNING - return future.result()
2020-07-22 20:00:43 = WARNING -   File "/usr/local/lib/python3.5/asyncio/futures.py", line 294, in result
2020-07-22 20:00:43 = WARNING -     
2020-07-22 20:00:43 = WARNING - raise self._exception
2020-07-22 20:00:43 = WARNING -   File …
=> version bump

CI/server_scripts/build_wall_e/Dockerfile.python_base, CI/server_scripts/build_wall_e/python-base-requirements.txt, documentation/Working_on_Bot/Docker-less/README.md
Increasing version of python used from `3.5.5` to `3.8.5`
1. If you are adding a new command....document. Document the following …
=> Alpine docker image version bump

CI/server_scripts/build_wall_e/create_prod_docker_image.sh
changing when the most recent commits gets recorded just to make the jenkins output more readable as this way only the most recent changes are shown in the list of files changed and not say the past 50 files if a commit long ago happened to be the one to change a foundational image
1. If your PR is doing …
=> Improve CI output on Jenkins

CI/server_scripts/build_wall_e/deploy_to_staging_discord_guild.sh
changing the logic for focusing on a previous commit in case the latest master commit is not yet present in the log history for a particular non-master branch
1. If your PR is doing something like adding a new line or removing a new line, CODEOWNERS reserve the right to ask that you undo that change unless …
=> updating logic for getting previous commit

CI/server_scripts/build_wall_e/deploy_to_staging_discord_guild.sh
removing line of code that overwrote the previous commit variable even when it was valid. …
=> fix Ci bug

CI/server_scripts/process_pr_action/process_pr_action.sh
=> fix script name

CI/server_scripts/clean_branch/clear_branch_env.sh
Discord channel names are always lowercase so branch_name has to be converted to lower case as well. …
=> fix for CI clean up for discord channel names

CI/server_scripts/build_wall_e/Jenkinsfile, CI/user_scripts/create-dev-docker-image.sh, documentation/Working_on_Bot/Docker-less/README.md, documentation/Working_on_Bot/README.md, wall_e/src/resources/utilities/config/config.py
improve readme so that instructions are more clear and add back discord notifier in Jenkinsfile …
=> Improve readme

documentation/Working_on_Bot/Test_Cases.md, wall_e/src/resources/cogs/frosh.py, wall_e/src/resources/locales/help.json, wall_e/src/resources/utilities/config/dev.ini, wall_e/src/resources/utilities/config/production.ini
added a new command to make embeds representing frosh teams. requested by John the frosh chair.  …
=> Vj frosh game embed cmd

CI/server_scripts/build_wall_e/docker-compose.yml, CI/server_scripts/clean_branch/clear_branch_env.sh, CI/server_scripts/process_pr_action/process_pr_action.sh, CI/user_scripts/docker-compose-mount-nodb.yml, CI/user_scripts/docker-compose-mount.yml, wall_e/src/resources/cogs/manage_cog.py, wall_e/src/resources/cogs/reminders.py, wall_e/src/resources/cogs/role_commands.py, wall_e/src/resources/utilities/config/dev.ini, wall_e/src/resources/utilities/config/production.ini
Adding logic so that the roles commands can only be called from the bot specific channel and will otherwise just dm user author to inform them of that.
1. If your PR is doing something like adding a new line or removing a new line, CODEOWNERS reserve the right to ask that you undo that change unless it was …
=> Restrict roles channels

CI/server_scripts/build_prod_image/Jenkinsfile_create_prod_image, CI/server_scripts/build_wall_e/create_prod_docker_image.sh
Creating a CI for doing regular docker pushes due to following changes from how long docker images are retained for free account: https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/
1. If your PR is doing something like adding a new line or removing a new line, …
=> Add ci for regular docker pushes

wall_e/src/resources/cogs/manage_cog.py
fix issue outlined in https://github.com/CSSS/wall_e/issues/320
1. If you are adding a new command....document. Document the …
=> fix variable used

wall_e/src/main.py
Removing the welcome message embed since moderators want to start using the new discord feature of [Rule Screening](https://support.discord.com/hc/en-us/articles/1500000466882-Rules-Screening-FAQ) instead.
1. If your PR is doing something like adding a new line or removing a new line, CODEOWNERS reserve the …
=> Remove welcome message
